== Bootstrapping Jenkins

=== Prerequisites

Before you bootstrap Jenkins into your cluster you would need to det up one. You can do that locally with https://github.com/kubernetes/minikube[Minikube] or create an AWS cluster as described on [this page] or another cluster from provider of your choice. For Minikube you can execute `minikube start --kubernetes-version=v1.7.0` and wait until it's all setup.

=== Running Jenkins

==== SSH Keys

Before you provision anything Jenkins would need SSH keys to checkout from GitHub. Generate SSH keys in the repository folder `ssh-keygen -t rsa -b 4096 -C "your_email@example.com" -N ""` and add them to GitHub accoutn that you would like Jenkins to use.

==== Cluster setup

You don't really need to run anything but `run-minikube.sh`. Here's what will happen:

* Namespace `jenkins` is created and set to the current `kubectl` context
* Keys are set to the Kubernetes secret storage
* Configuration map is created for Kubernetes master URL
* Kubernetes deployment is applied

==== Init Containers

In order to get the configuration to Jenkins node there are some initContainers that are being run in the pod before starting the main container.

To join all the results an store them across the containers in the pod volume `ref-volume` is used - yo can see that it's mounted as `${JENKINS_HOME}/ref` folder to every init container.

https://github.com/ClearPointNZ/connect-jenkins-bootstrap/blob/master/jenkins.yml#L40-L53[Checkout container] sets up SSH keys and checks out the repository from GitHub.

https://github.com/ClearPointNZ/connect-jenkins-bootstrap/blob/master/jenkins.yml#L54-L62[Install plugins container] installs plugins listed in the `plugins` file to the `${JENKINS_HOME}/ref` folder for Jenkins to pick them up on startup

https://github.com/ClearPointNZ/connect-jenkins-bootstrap/blob/master/jenkins.yml#L63-L81[Override config container] updates the Jenkins host and Kubernetes master host values in the `config.xml.override` using `scripts/hack-jenkins-env.sh`. Then it copies updated config to `${JENKINS_HOME}/ref` folder so it's picked up by Jenkins when it starts up. Also it copies `scripts/security.groovy` to `${JENKINS_HOME}/ref/init.groovy.d/`. When Jenkins starts up it executes all Groovy sccripts from that folder. `security.groovy` sets up the `admin` user and initial password and Jenkins API token.

https://github.com/ClearPointNZ/connect-jenkins-bootstrap/blob/master/jenkins.yml#L82-L90[Copy jobs container] copies predefined job `config.xml` to `${JENKINS_HOME}/ref` folder.

==== Jenkins container

As the Jenkins container starts it runs scripts and copies plugins as described in https://github.com/jenkinsci/docker[Jenkins CI Docker image docs]. In our setup we avoided running Jenkins install wizard by setting environment variable `JAVA_OPTS=-Djenkins.install.runSetupWizard=false`.

To demonstrate that the environment is working and creating slaves to execute a job main container has a postStart hook that runs `scripts/wait-for-jenkins-and-run-job.sh` that waits until Jenkins API is awailable and then triggers a job `test` that is restricted to run on a slave node. To authenticate is uses admin API token that is generated by the `scripts/security.groovy`.
